### ISSUE TITLE
Run portindex2json.tcl on Buildbot

### ISSUE THREAD

**Issue by arjunsalyan** [macports/macports-webapp#11]
It has been mentioned in https://github.com/macports/macports-contrib/pull/2#issuecomment-473679395 that it would make sense to generate portindex.json on our server and provide it alongside the regular port indices for various operating systems.

Our portindex is currently created at two different locations:
* At https://github.com/macports/macports-infrastructure/blob/master/jobs/mprsyncup as a "cronjob".
* [On the buildbot configuration](https://github.com/macports/macports-infrastructure/blob/2343a696d5897ecece48ef2212e9b4fb49b47923/buildbot/master.cfg#L749) after each commit. The postgresql then gets submitted to our server.

The json file should be generated at either of these two steps. If we create it via buildbot (next to `portindex2sql`), it would hopefully be updated faster. But the second question is whether it makes any sense to somehow merge the two steps.

@mojca's understanding has been that to a certain extent we are updating our portindex with some delay on purpose, so that users would hopefully get the ports in binary form by the time the portindex reaches them. Maybe we can also discuss if the current system needs any changes.

Not as part of this task, but we may also try to address https://trac.macports.org/ticket/55471.

@macports/infrastructure @rajdeepbharati

**Comment by raimue** [comment]
What does the webapp use the JSON file for? Will the PortIndex data be imported regularly? Would it be desirable to fill the database directly instead? The database for the current ports search page on the website is filled from the buildbot, but to which location should we deploy a resulting JSON file? How would the webapp be triggered to use it?

I think adding another step to mprsyncup and always distribute a `PortIndex.json` with the ports tree would be the easiest solution. Then this PortIndex would also always reflect what is available from mirrors. Mirrors of the ports tree are arbitrarily delayed as the sync happens only every few hours or daily. I do not think that the delay is on purpose, but as described it helps with the provisioning of binary archives.

Personally, I would not worry about https://trac.macports.org/ticket/55471 at all. It is only for legacy systems.

**Comment by mojca** [comment]
> What does the webapp use the JSON file for?

Well, another point is that repology would be more than happy to have this file available, but with respect to the webapp, this is a bit of "fluid answer".

Ideally the webapp would be updated immediately after each commit. The portindex can of course (and probably will at some point) be generated locally. It's not yet absolutely clear what the most efficient frequent update method will be.

> Will the PortIndex data be imported regularly?

Yes.

> Would it be desirable to fill the database directly instead?

I'm not sure. To some degree I would prefer to get some source of information in a somewhat stable format (json sounds ok) and let the web app find the optimal way of handling that information. Ideally we would want just differential data (which ports were removed, which ones were updated; it should not hurt to get full data of updated ports).

Again, I'm not yet sure if this should better be triggered from the buildbot or locally every N seconds, or how it will be done at the end.

We still need to find a way to deploy the app in Docker, and we need to put MacPorts inside the docker. If we do both soon, the best strategy for updates may change.

> The database for the current ports search page on the website is filled from the buildbot, but to which location should we deploy a resulting JSON file?

I would put it next to the regular portindex for now (I forgot the location of that one).
To communicate with the app my favourite would be to send a small json object listing deleted files, plus new files with extra information. But that code still needs to be written on both ends.

For now I wouldn't mind if the app would sync the portindex.json file from the server (instead of portindex followed by running portindex2json locally) every 30 minutes, get the info about updated paths via, say, some git foo, and only extract the info about the relevant ports from the full portindex.json. I would say that it would be nice if the json file optionally contained the git shasum from which it was generated (if that info was somehow available).

If I did the updating part myself, I would run macports locally, and then every N seconds update via git, check which paths were changed in each commit, store each commit + modified paths to the database, run portindex (then portindex2json) after each commit, and finally

> How would the webapp be triggered to use it?
> 
> I think adding another step to mprsyncup and always distribute a `PortIndex.json` with the ports tree would be the easiest solution. Then this PortIndex would also always reflect what is available from mirrors. Mirrors of the ports tree are arbitrarily delayed as the sync happens only every few hours or daily. I do not think that the delay is on purpose, but as described it helps with the provisioning of binary archives.

In that case let's simply do it in `mprsyncup` for now.

**Comment by arjunsalyan** [comment]
> In that case let's simply do it in `mprsyncup` for now.

I would start the work on this- but I am having difficulties understanding this file [mprsyncup](https://github.com/macports/macports-infrastructure/blob/master/jobs/mprsyncup), not sure how exactly do I start.

**Comment by umeshksingla** [comment]
Too many variables, I know. Try to go through the code as a shell script and substitute variables for their values from the top. 

It essentially just fetches the latest code from the macports-base repository and checks if it is updated with the last version fetched. You can infer it from L126: 

`[ "${RBASE_OLD_REV}" = "${RBASE_NEW_REV}" ] && RBASE_CHANGED=0` 

where `RBASE_OLD_REV` and `RBASE_NEW_REV` are simply the latest commits before and after `git pull`.
Same for macports-ports repository.

If the base has changed then it is built again (L152-L167) and ports are regarded as changed too (L151). Then it simply loops through all the platforms and builds portindex for each (L177) in background. This is where you need to add that extra step.

`${PORTINDEX} -p "macosx_${PLATFORM}" -o "${INDEX}"`

Lastly, if any of the base, ports or portindex have been updated, it generates and signs tarballs for those (L202-L217) and replaces them in the rsync server (L226 - L242). You can really just ignore all that hard-linking stuff.

@raimue 
I assumed that "replacing files on the rsync server" is possible because it works as if it's mounted on the folder `/rsync/macports` on the machine where the script is run. Am I correct? I do not know much about how rsync works. 
Also, when you say adding an extra step in `mprsyncup`, do you mean something like passing an extra argument `--json` to the portindex command and add the code there?

**Comment by ryandesign** [comment]
> I assumed that "replacing files on the rsync server" is possible because it works as if it's mounted on the folder `/rsync/macports` on the machine where the script is run. Am I correct?

We run mprsyncup on the same machine which is the private rsync server. It runs a slightly patched version of mprsyncup, including changing RSYNCROOT to the location where the files are actually located on the server. The public rsync server (rsync.macports.org) periodically connects to the private rsync server to get whatever has changed.

**Comment by arjunsalyan** [comment]
I am looking for some advice about the right place to fetch from and store `portindex2json.tcl`. It is currently available at [macports-contrib/portindex2json](https://github.com/macports/macports-contrib/tree/master/portindex2json). Thanks

**Comment by mojca** [comment]
The script clones both ports and base. Maybe the easiest thing to do would be to simply clone `macports-contrib` along with the two and use `portindex2json` from that clone. Or at least that's what I would probably do. This will also ensure that you'll always use the latest version of the script. If you just ask Ryan to install the script somewhere and use it directly, it will also get outdated.

**Comment by raimue** [comment]
@umeshksingla 
> I assumed that "replacing files on the rsync server" is possible because it works as if it's mounted on the folder `/rsync/macports` on the machine where the script is run. Am I correct? I do not know much about how rsync works.

Yes, the output of the mprsyncup script is a directory that will be served by rsync. The rsync protocol is used to replicate this directory on another machine.

> Also, when you say adding an extra step in `mprsyncup`, do you mean something like passing an extra argument `--json` to the portindex command and add the code there?

Not necessarily, as I think adding this to base will be a lot more work and also requires a base release before it can be used in the mprsyncup script. I would not rule this out as a later goal, though.

Just start with the existing portindex2json.tcl script that we have in macports-contrib.

**Comment by mojca** [comment]
This was finished in week 5.
