### ISSUE TITLE
Setup HttpStatusPush on Buildbot

### ISSUE THREAD

**Issue by arjunsalyan** [macports/macports-webapp#12]
If 0.8.14 and 2.3.0 send almost the same JSON, then we could deploy it on the official buildbot setup immediately. And if not, then it probably makes sense to stick to 2.3.0 only.

http://docs.buildbot.net/2.3.0/manual/configuration/reporters.html
http://docs.buildbot.net/0.8.14/manual/configuration.html

@ryandesign @rajdeepbharati

**Comment by rajgoesout** [comment]
> Note
> The json data object sent is completely different from the one that was generated by 0.8.x buildbot. It is indeed generated using data api.

http://docs.buildbot.net/2.3.0/manual/configuration/reporters.html#httpstatuspush

**Comment by arjunsalyan** [comment]
> > Note
> > The json data object sent is completely different from the one that was generated by 0.8.x buildbot. It is indeed generated using data api.
> 
> http://docs.buildbot.net/2.3.0/manual/configuration/reporters.html#httpstatuspush

Hmm. Thanks. Then we should probably set it up on the upgrade you have planned.

**Comment by rajgoesout** [comment]
@arjunsalyan What json spec do you need?
Or do you want me to send the default: https://docs.buildbot.net/latest/manual/configuration/reporters.html#json-object-spec

**Comment by arjunsalyan** [comment]
> @arjunsalyan What json spec do you need?
> Or do you want me to send the default: https://docs.buildbot.net/latest/manual/configuration/reporters.html#json-object-spec

The information needed about a build is (@mojca: could you please verify this):
- builder name
- build id
- watcher id
- port name
- port version
- start time
- time elapsed
- status

**Comment by rajgoesout** [comment]
> The information needed about a build is (@mojca: could you please verify this):

Okay, I will customize the request

**Comment by arjunsalyan** [comment]
Thank you.

**Comment by mojca** [comment]
* For status it probably makes sense to store two separate things (as I mentioned who-remembers-where a while ago):
  * Numeric status that's equal to Buildbot's own code (0 = success, 1 = ...)
  * String value (`Failed install dependencies of git`)
* For time elapsed it could be kind of cool to separately store the build time of the port itself, as well as the total build time (including activation of dependencies).
* "watcher id" means "build number on the watcher" (under assumption that the configuration actually stays like it is now; I'm not sure if we will still need this info, but we can of course keep it)
* "build id" alone will now have a different meaning than in 0.8. Now each port will probably be built on its own builder, so those numbers will run from 1 onwards for every port individually

I now asked on IRC if it would be feasible to support URLs like `.../#/builders/python37/builds/3` as an alias for `.../#/builders/247/builds/3`.

@arjunsalyan: this data should really be marked with a different API version somewhere, so that you can construct a different URL for the links to the new vs. the old buildbot setup. During the testing period of the new setup you may want to exclude these results from port health queries etc.

**Comment by rajgoesout** [comment]
`.../#/builders/247/builds/3` here builderid is 247 and number (build number) is 3 (buildid may be different)
For example, in
http://ec2-18-188-105-249.us-east-2.compute.amazonaws.com/api/v2/builds/2
buildid is 2 (2nd build of ALL builds in this buildmaster setup) and number is 1 (1st build of builderid 4).

**Comment by mojca** [comment]
Regarding the mention of my request above, there's already a ticket for that:
https://github.com/buildbot/buildbot/issues/3465 (it was mentioned on IRC).

**Comment by mojca** [comment]
> `.../#/builders/247/builds/3` here builderid is 247 and number (build number) is 3 (buildid may be different)
> For example, in
> http://ec2-18-188-105-249.us-east-2.compute.amazonaws.com/api/v2/builds/2
> buildid is 2 (2nd build of ALL builds in this buildmaster setup) and number is 1 (1st build of builderid 4).

In the quoted API the builderid is 4, but that piece of information is not as useful as it could be.

On 0.8 we actually have builder name rather than builder id:
* https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/34570
The URL uses `ports-10.14_x86_64-builder` rather than some "random builder number" as is the case in the latest version.
And also the [api](https://build.macports.org/json/builders/ports-10.14_x86_64-builder/builds/34570?as_text=1) would return
    ```
    "builderName": "ports-10.14_x86_64-builder", 
    ```
    which is something I'm clearly missing in the new API.

**Comment by rajgoesout** [comment]
> which is something I'm clearly missing in the new API.

You can get builderName from http://ec2-18-188-105-249.us-east-2.compute.amazonaws.com/api/v2/builders

> The URL uses ports-10.14_x86_64-builder rather than some "random builder number" as is the case in the latest version.

Okay I will look into this issue

**Comment by mojca** [comment]
> > which is something I'm clearly missing in the new API.
> 
> You can get builderName from http://ec2-18-188-105-249.us-east-2.compute.amazonaws.com/api/v2/builders

OK, but probably using one level deeper, for example http://ec2-18-188-105-249.us-east-2.compute.amazonaws.com/api/v2/builders/4 directly to get the name just for the 4th builder.

Does that mean that buildbot would send some info to the app, but then app would make additional API calls back to the buildbot to get more information?

> > The URL uses ports-10.14_x86_64-builder rather than some "random builder number" as is the case in the latest version.
> 
> Okay I will look into this issue

This is a relatively low priority though. Just keep working on the more pressing / higher priority ones for now.

Thanks.

**Comment by rajgoesout** [comment]
@arjunsalyan Could you please tell me how to test this? (how did you check what response was sent)

**Comment by arjunsalyan** [comment]
> @arjunsalyan Could you please tell me how to test this? (how did you check what response was sent)

I created a temporary view, started the server and setup HttpStatusPush to post to that view's route. There can be other workarounds also.

**Comment by arjunsalyan** [comment]
I would be in favor of closing this now. The app supports parsing the requests received from buildbot2's `HttpStatusPush`, and other issues related to Buildbot would be better addressed in the relevant repositories.
