### ISSUE TITLE
Group subports

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#18]
When displaying all ports, all ports belonging to a particular maintainer etc. we would sometimes like to group subports (sharing the same path) together.

**Comment by arjunsalyan** [comment]
Without any redesigns to tables and just by some manipulation in the table- this could be achieved. But there is a problem due to pagination. There might be cases when some of the sub-ports will be on the next page, and by nature they will be folded but the parent that should unfold them would be left on the previous page- so they will never show. To avoid this situation we may have them unfolded by default. Please see this: http://frozen-falls-98471.herokuapp.com/maintainer/github/mojca/

**Comment by jmroot** [comment]
There's some formatting weirdness sometimes, for example: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/maintainer/github/jmroot/

That displays py*-gdbm in the same box as py*-game as though they were subports. Likely something is going wrong because py-gdbm does not have the same maintainer and so is not listed.

**Comment by arjunsalyan** [comment]
Thank you. This was happening when the parent port of the subports was not maintained by the same maintainer, as you suggested. It has been fixed now.
