### ISSUE TITLE
Port detail page returns HTTP 500 for ports where the case changed

### ISSUE THREAD

**Issue by Janosch** [macports/macports-webapp#263]
I recently renamed some of my ports to match the case of the corresponding github project:

macpass -> MacPass
boca -> BoCA

There are two problems concerning the macports web app:
- The obsolete name is still displayed (in this example the lowercase names)
- Opening the port detail page for **both** spellings returns a HTTP 500 error

Steps to reproduce:

1. Open the URLs
https://ports.macports.org/?search=macpass
https://ports.macports.org/?search=boca

2. Open the port details pages
3. HTTP 500 is returned

**Comment by arjunsalyan** [comment]
This problem is occuring because the `GET` query is getting two results here: https://github.com/macports/macports-webapp/blob/af79b281b180c8d9572abef2183fcea5f35882f3/app/ports/views.py#L114

We have had this issue in the past also, and the root cause lies in the code that updates the port information (it creates a duplicate port when case changes).

This and a lot of other issues with the website have been fixed in a major upgrade. The upgrade is ready with the coding sitting in `gsoc2020` branch https://github.com/macports/macports-webapp/tree/gsoc2020 . As of now, we lack infrastructure resources to host this new version - but efforts are being made to get it up soon.

To fix the issue at hand, we need help from @neverpanic to delete those duplicate entries from the database.

**Comment by neverpanic** [comment]
Fixed by #265.
