### ISSUE TITLE
Request Maintainer for specific apps

### ISSUE THREAD

**Issue by dnet890** [macports/macports-webapp#285]
Hi
I am just curious that how to request maintainers/somebody to make apps even for beta or dev version to be available on macports? because I only find this one (https://ports.macports.org/statistics/faq/) Please advise. Thanks

**Comment by mojca** [comment]
These issues are only meant for feature requests and bug reports for the website (https://ports.macports.org), so this is a bit off-topic for this particular tracker.

The official bug / feature tracker is here: https://trac.macports.org/wiki/Tickets. You can log in with github, I believe there's no need to make a new account in order to be able to open a request for a new port.

As a general advice: while these tickets are being watched, it's somewhat unlikely that someone will just pick up a request for a new port (it's possible that someone does, but more likely that this won't happen unless the software you are requesting is either very easy to add or popular enough, or maybe you are simply lucky enough). If you really want something to be packaged, it makes sense to ask on the mailing list and ideally be willing to work on it yourself, with others helping you achieve the result that you want.

This FAQ that you linked to is only about the website itself. But maybe that's a good hint that we may want to add further questions there, pointing users to other resources.

**Comment by dnet890** [comment]
Thanks for your reply. By the way, macports repository is not available for the proprietary based app. Is that so?

**Comment by mojca** [comment]
Proprietary apps are a bit of a sensitive topic. Generally the answer is no, but there might be some extremely extremely rare exceptions.

Just to make it clear: you can always set up port definitions in a separate, unofficial repository that can be shared among a large group of users. That should still make the ports easy to install / uninstall / upgrade etc.

I will close this ticket here since it's unrelated for this particular repository, but feel free to ask via IRC (mirrored over rocket chat) or via mailing list, or open a ticket on trac in case you have a specific request.
