### ISSUE TITLE
Old search links don't work anymore

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#321]
Old port search links in the wild don't work anymore. For example:

https://www.macports.org/ports.php?by=name&substr=subversion

ports.php is still around, exclusively to redirect these requests to their new equivalents. It redirects to:

https://ports.macports.org/?search=subversion&search_by=name

I would expect that to search for subversion, but it just displays the main ports page.

**Comment by arjunsalyan** [comment]
I remember having this on my bucket list sometime while deploying the new website. I believe that this redirect should be fixed in macports-www itself. The old `ports.php` was written in accordance with the old macports-webapp, and having a reverse logic in new macports-webapp would only complicate things.

https://github.com/macports/macports-www/pull/26

**Comment by ryandesign** [comment]
It can be changed in ports.php; sure. But presumably https://ports.macports.org/?search=subversion&search_by=name worked with the previous version of the web app, or we wouldn't have put that redirect into ports.php in the first place. Therefore, in order to preserve that style of link that might be out there in the wild, the new web app should also accept those old URLs.
