### ISSUE TITLE
Port pdfpc is missing

### ISSUE THREAD

**Issue by larer** [macports/macports-webapp#323]
Hi,

New to submitting issues, so I don't know if this is the appropriate way.Please be gentle on me as I'm a novice here.

I have used "pdfpc" to my liking previously, but with a new machine and new port install I fail to install it.
I cannot install the port pdfpc any longer, but now with a new Mac I cannot install it. It is not available on the site:
https://packages.macports.org/pdfpc
Trying to access this gives a 404.

Has anyone succeeded with a "sudo port install pdfpc" recently?

Kind regards,
Lars

**Comment by mojca** [comment]
Dear @larer,

This particular issue tracker is only related to the website https://ports.macports.org/ itself, not to other macports-related issues like broken ports.

The port summary page https://ports.macports.org/port/pdfpc/details/ says that the port failed to build on all the platforms with a buildbot worker (10.6 to 12), but there is no ticket about it yet. If a port fails to build, you won't be able to find it under packages.macports.org either.

@mascguy, @landonf or @maehne might be able to help, but it's best to discuss the problem within the appropriate tracker.
Please open a new ticket under https://trac.macports.org/newticket (you can simply login to that site with your github account).  In case nobody responds to the ticket, you may write to the mailing list (user or developer) or ask on IRC or rocket chat.

The buildbot logs say
```
-- Checking for module 'libmarkdown'
--   No package 'libmarkdown' found
```
which sounds like either a missing dependency or a broken check for dependencies. Our buildbot logs date back to 2019 and there hasn't been any successful build since then. That's weird though since there have been relatively recent commits upgrading the port. I assume that the one doing the upgrade must have successfully built it locally at that time.

I will close this ticket now, but please continue at Trac or at one of our discussion channels.

**Comment by larer** [comment]
Hi!
Thanks for your super fast response!
How can I make a request for a new port. I would like to have the tool pympress in MacPorts (that I am using) this particular package is available in brew, so it should be possible to get it on MacPorts too...
Sorry for being such a Newbee...
Kind regards,
Lars Eriksson

**Comment by mascguy** [comment]
> Hi! Thanks for your super fast response! How can I make a request for a new port. I would like to have the tool pympress in MacPorts (that I am using) this particular package is available in brew, so it should be possible to get it on MacPorts too... Sorry for being such a Newbee... Kind regards, Lars Eriksson

No worries Lars, we're all happy to help!

New ports can be requested via the same process as bug reports. But when creating the ticket, set the "Type" field to "Request."

Here's an example of a new port request, which I recently submitted:
[63819 - tink/py-tink: new port request](https://trac.macports.org/ticket/63819)
