### ISSUE TITLE
sudo: port command not found--------already update environment

### ISSUE THREAD

**Issue by DeliaLing** [macports/macports-webapp#369]
Hello, 
I am facing below issue after installed Macports from website, I searched from google that it could be environment variable issue, so I added port in PATH as below, please have a look this issue, thanks.

++++++++++++++++++++++++++++++++++++=
Last login: Thu Feb  1 15:55:26 on ttys000
linzha02@CRP-MAC-NUAMD6N ~ % sudo port install putty
sudo: port: command not found
linzha02@CRP-MAC-NUAMD6N ~ % echo $PATH
/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/CyberArk EPM.app/Contents/Helpers:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/linzha02/Library/Android/sdk/emulator:/Users/linzha02/Library/Android/sdk/platform-tools:/Users/linzha02/Library/Android/sdk/tools:/Users/linzha02/Library/Android/sdk/tools/bin:/opt/local/bin/:/opt/local/sbin/
linzha02@CRP-MAC-NUAMD6N ~ % port -v
MacPorts 2.9.1
Entering shell mode... ("help" for help, "quit" to quit)
[Users/linzha02] >

**Comment by jmroot** [comment]
Your sudo configuration is likely modifying PATH.

Closing because this issue tracker is for issues related to macports-webapp (the website running at ports.macports.org) only.

For reporting issues related to ports and MacPorts software, please use Trac:
- Trac: https://trac.macports.org
- Existing Tickets: https://trac.macports.org/wiki/Tickets

To ask for help or otherwise discuss using MacPorts, please use the channels listed at https://www.macports.org/contact.php.
