### ISSUE TITLE
Website lists rust port as deleted

### ISSUE THREAD

**Issue by mqudsi** [macports/macports-webapp#374]
The `rust` port is not deleted (see below) but the website shows the red warning banner up top that claims otherwise.

![image](https://github.com/user-attachments/assets/27f5186c-e1cf-4865-8a47-019a41ce595e)

```
> sudo port info rust
rust @1.78.0 (lang, devel)
Sub-ports:            rust-src
Variants:             mirror_all_architectures, universal

Description:          Rust is a curly-brace, block-structured expression language. It visually resembles the C language family, but differs significantly in syntactic
                      and semantic details. Its design is oriented toward concerns of "programming in the large", that is, of creating and maintaining boundaries --
                      both abstract and operational -- that preserve large-system integrity, availability and concurrency.
Homepage:             https://www.rust-lang.org

Build Dependencies:   cmake, python312, pkgconfig, ninja, clang-16, legacy-support
Library Dependencies: curl, libiconv, libgit2, zlib, openssl3
Platforms:            darwin >= 9
License:              (MIT or Apache-2) and BSD and zlib and NCSA and Permissive
Maintainers:          Email: mcalhoun@macports.org, GitHub: MarcusCalhoun-Lopez
                      Policy: openmaintainer
```

**Comment by jmroot** [comment]
Probably failing to parse on the system running the web app again (cf. #342). @MarcusCalhoun-Lopez

**Comment by arjunsalyan** [comment]
Yes, here are the logs for `portindex -p macosx_19_i386 -x`

```
Failed to parse file lang/lfortran/Portfile: invalid command name "test.ignore_archs"
Error: Rust PG: unable to find SDK for 
Failed to parse file lang/rust/Portfile: 
Error: Rust PG: unable to find SDK for 
Failed to parse file lang/rust-bootstrap/Portfile: 
Failed to parse file mail/courier-imap/Portfile: invalid command name "test.ignore_archs"
```

**Comment by jmroot** [comment]
`test.ignore_archs` should be valid if running the current version of base. Guess the other one is a bug in the rust portgroup.

**Comment by jmroot** [comment]
It's still probably a bad idea to throw an error in something that is called at the top level of Portfiles (i.e. outside any phase), but that should fix the immediate problem.

**Comment by mqudsi** [comment]
Maybe just handle “port deleted” specifically then throw up a yellow warning “info might be stale” or similar on any unhandled errors? (Instead of “port deleted” being the catch-all case.)

**Comment by ryandesign** [comment]
> Maybe just handle “port deleted” specifically

How? The web app does not receive notification of each change that occurs in the repository. It merely imports portindexes generated at different points in time. If a port was in the index the last time the import ran and is not in the index now, the web app can only infer that it has been deleted.

**Comment by mqudsi** [comment]
Maybe I’m not seeing the whole picture, but what I am suggesting is that “failed to parse portindex snapshot” (exception) be treated differently from “entry not found in portindex snapshot to begin with”.

One way for what I’m thinking is that a sentinel value for failed parses could be used so that it’s still in the index to differentiate it from cases where there is no entry at all?

**Comment by ryandesign** [comment]
So you're suggesting that, rather than just running portindex, the web app should run portindex and parse its stdout and stderr to determine if an error occurred when parsing an entry, and then record that port in the database as existing but failing to parse, rather than recording it as being deleted. It's messy but possible. It may be a lot of work to do to fix a problem that should never exist in the first place. In other words, everyone should exercise continuous vigilance to ensure our ports never fail to parse.

**Comment by mqudsi** [comment]
I wasn’t certain whether the parsing happened in a separate process but yes, that’s pretty much the essence of my suggestion.

But if we say let’s do it as you recommend, then is there something we can add to CI (edit: port-side) perhaps that ascertains parsing succeeds?

**Comment by ryandesign** [comment]
Yes, the portindex is generated by the standard MacPorts program `portindex` and then converted into a database by another script.

The [CI workflow](https://github.com/macports/macports-ports/blob/master/.github/workflows/main.yml) [bootstrap script](https://github.com/macports/macports-ports/blob/master/.github/workflows/bootstrap.sh) does already download a recent portindex and then run `portindex` to update it, but does nothing special if that fails.

Generating a new portindex from scratch takes a long time. Updating an existing recent portindex is much faster.

Certainly if the port being changed by a PR did not parse on macOS, that should cause the build to fail and should be noticed in PR review.

The problem here is not that the port failed to parse generally, but that it failed to parse on Linux, which nobody tests on.

Could we add CI that checks if the portindex generates cleanly for Linux and for every macOS version we care about? Probably. For Linux we do not have a server-side generated portindex so it would take a long time to generate it from scratch in CI. Could we add generation of a Linux portindex to [`mprsyncup`](https://github.com/macports/macports-infrastructure/blob/master/jobs/mprsyncup) to speed that up? Sure, on the `PLATFORMS=` line.

None of this helps at all if someone commits a portindex-breaking change to a port without using a pull request since that would bypass all the CI checks. MacPorts does not have a policy of requiring pull requests; project members are allowed to commit to master directly.

So again, lots of technological solutions could be implemented that would take time and be incomplete when what is need is just for people to write portfiles correctly—for the sake of portindexing and for all other reasons.

**Comment by jmroot** [comment]
We've discussed previously that something that would be helpful is if the web app made the output of its most recent `portindex` run available somewhere.
