### ISSUE TITLE
PyQt6?

### ISSUE THREAD

**Issue by mo5kv** [macports/macports-webapp#376]
One of those Amateur Radio guys trying to get NanoVNA to work.
I have reached the situation where PyQt6 is required.
...Davids-Mac-mini:NanoVNASaver applesmacmini$ python3.9 NanoVNASaver.py
...Traceback (most recent call last):
...File "/Users/applesmacmini/nanovna-saver/src/NanoVNASaver/NanoVNASaver.py", line 25, in <module>
...from PyQt6 import QtWidgets, QtCore, QtGui
...ModuleNotFoundError: No module named 'PyQt6'
SO I attempted to install it. 
...Davids-Mac-mini:NanoVNASaver applesmacmini$ sudo port install py39-pyqt6
...Password:
...--->  Computing dependencies for py39-pyqt6
Still waiting 1 hr later. If I close the terminal window it gives me the message:
Closing this window will terminate the running processes tclsh8.6 sudo.
Will wait overnight (Australia) so maybe I will get an answer
Checking the ports installed,
...py39-pyqt5 @5.15.11_0 (active)
...py39-pyqt5-sip @12.15.0_0 (active)
  I am not a programmer, just have a few skills from the ancient DOS era.

**Comment by jmroot** [comment]
Closing because this issue tracker is for issues related to macports-webapp (the website running at ports.macports.org) only.

For reporting issues related to ports and MacPorts software, please use Trac:
- Trac: https://trac.macports.org
- Existing Tickets: https://trac.macports.org/wiki/Tickets

To ask for help or otherwise discuss using MacPorts, please use the channels listed at https://www.macports.org/contact.php.
