### ISSUE TITLE
Web site displays someone else's username

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#379]
When visiting https://ports.macports.org just now, it showed someone else's username in the drop down menu at the upper right:

![Screen Shot 2024-10-02 at 2 27 21 AM](https://github.com/user-attachments/assets/b1b3a3ea-7311-4fb3-9c80-10a1300c62fa)

I was not logged in at the time. When I refreshed the page it changed to the more familiar view when I am not logged in, where that menu says "Watchlist" instead of a username.

Is there maybe a caching problem? Caching pages that have a logged-in user's username on them?

**Comment by arjunsalyan** [comment]
The only possible cause of this is caching only. But the current setup is ideally supposed to disable caching for pages which use cookies. Maybe recent changes I did to address https://github.com/macports/macports-webapp/issues/378 might have broken something. I have reverted them for now, and that seems to fix this.

**Comment by jmroot** [comment]
The site lost my "always skip to details" setting a couple times before you made those changes.

**Comment by arjunsalyan** [comment]
> The site lost my "always skip to details" setting a couple times before you made those changes.

This happened because of another change which specifically ignored the cookies, it was done earlier when the server was facing performance issues.

I have now upgraded the server and reverted all the caching settings to as before. Performance seems better now. Current caching logic is:

- Cache pages for 1 hour if there are no cookies.
- Bypass cache if there are cookies.
