### ISSUE TITLE
Xcrysden for Sequoia

### ISSUE THREAD

**Issue by sherheroes** [macports/macports-webapp#380]
It seems that Xcrysden cannot be installed on macOS Sequoia due to issues with installing Togl-2.0.

port install Togl-2.0
--->  Computing dependencies for Togl-2.0
--->  Building Togl-2.0
Error: Failed to build Togl-2.0: command execution failed
Error: See /Users/macports/var/macports/logs/_Users__macports_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_x11_Togl-2.0/Togl-2.0/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port Togl-2.0 failed

**Comment by neverpanic** [comment]
Closing because this issue tracker is for issues related to macports-webapp (the website running at ports.macports.org) only.

For reporting issues related to ports and MacPorts software, please use Trac:

- Trac: https://trac.macports.org/
- Existing Tickets: https://trac.macports.org/wiki/Tickets

To ask for help or otherwise discuss using MacPorts, please use the channels listed at https://www.macports.org/contact.php.

**Comment by sherheroes** [comment]
> Closing because this issue tracker is for issues related to macports-webapp (the website running at ports.macports.org) only.
> 
> For reporting issues related to ports and MacPorts software, please use Trac:
> 
> * Trac: https://trac.macports.org/
> * Existing Tickets: https://trac.macports.org/wiki/Tickets
> 
> To ask for help or otherwise discuss using MacPorts, please use the channels listed at https://www.macports.org/contact.php.

Sorry wrong places, but thanks for the help!
