### ISSUE TITLE
can not build root6 using Sequioa arm64

### ISSUE THREAD

**Issue by evagena** [macports/macports-webapp#381]
--->  Fetching archive for tiff
--->  Attempting to fetch tiff-4.7.0_0.darwin_24.arm64.tbz2 from https://packages.macports.org/tiff
--->  Attempting to fetch tiff-4.7.0_0.darwin_24.arm64.tbz2 from https://vie.at.packages.macports.org/tiff
--->  Attempting to fetch tiff-4.7.0_0.darwin_24.arm64.tbz2 from https://nue.de.packages.macports.org/tiff
--->  Configuring tiff
Error: Failed to configure tiff: consult /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_graphics_tiff/tiff/work/tiff-4.7.0/config.log
Error: Failed to configure tiff: configure failure: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_graphics_tiff/tiff/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port root6 failed

**Please make sure the Issue you are creating is related to macports-webapp (the website running at ports.macports.org) only.**

For issues related to ports and MacPorts software, please use Trac:
- Trac: https://trac.macports.org
- Existing Tickets: https://trac.macports.org/wiki/Tickets

**Comment by jmroot** [comment]
Closing because this issue tracker is for issues related to macports-webapp (the website running at ports.macports.org) only.

For reporting issues related to ports and MacPorts software, please use Trac:
- Trac: https://trac.macports.org
- Existing Tickets: https://trac.macports.org/wiki/Tickets
- Please check the problem hotlist before reporting an issue: https://trac.macports.org/wiki/ProblemHotlist

To ask for help or otherwise discuss using MacPorts, please use the channels listed at https://www.macports.org/contact.php.
