### ISSUE TITLE
Access to https://trac.macports.org/ forbidden (403) from PPC MacOS X 10.4.11, Tiger, with latest edition of TenFourFox

### ISSUE THREAD

**Issue by ballapete** [macports/macports-webapp#382]
Exactly this is the case. The interesting thing is that I switched off my PowerBook a few days ago and booted it five or six hours ago. All old tabs to tickets on https://trac.macports.org/ opened without problem, I can work there, and am obviously logged in there since a few days. But new connections possible, no search, no visiting other issues.

**Comment by ballapete** [comment]
Same with the system's Safari 4.1.3.

**Comment by ballapete** [comment]
Same failure with iCab.

**Comment by ballapete** [comment]
Netscape Navigator 9 has problems as well, first with seamonkey.at, then MacPorts site.

**Comment by ballapete** [comment]
TenFourFox was fooling me! All open and ready for work issues were just memories of the last state before quitting TenFourFox. Nothing goes.

**Comment by neverpanic** [comment]
That's probably caused by me — we had gazillions of requests from bots that didn't identify themselves as bots but instead used old Chrome and Firefox user agents, which trac is now configured to filter. See https://trac.macports.org/ticket/71358 (which I know you can't see, at least not with TenFourFox).

Can you tell me the user agent that your TenFourFox uses so I can make sure that doesn't land on our blocklist?

**Comment by ballapete** [comment]
Mozilla/5.0 (Macintosh; PPC Mac OS X 10.4; FPR32; rv:45.0) Gecko/20100101 Firefox/45.0 TenFourFox/7450

**Comment by ballapete** [comment]
I am using the same version of TenFourFox on Mac OS X 10.5.8, Leopard. It's really the same physical package. Could be it is substituting "10.4" with "10.5". A check might happen some time in December… (too much work on Tiger)

**Comment by neverpanic** [comment]
Let's continue the discussion at https://trac.macports.org/ticket/71402

**Comment by ballapete** [comment]
Yes, seems to work again (reload, search, GitHub login).
