### ISSUE TITLE
list ports by name ranges

### ISSUE THREAD

**Issue by lemzwerg** [macports/macports-webapp#49]
Looking at

http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/ports/category/textproc

I see that there are 1285 ports in this category.

![textproc-ports](https://user-images.githubusercontent.com/1630245/62002587-6f32d300-b107-11e9-9cdc-b3313115ace4.png)

For example, page 1 shows package 'a2ps-j' to 'cmph', page 2 gives 'coccinelle' to 'html-xml-utils'.  It would be great if this information is shown for navigation, too:
```
  «  1 (a2ps-j – cmph)  2 (coccinelle – html-xml-utils)  ...  »
```

**Comment by mojca** [comment]
A similar request recently came from @mf2k (https://github.com/macports/macports-webapp/issues/39#issuecomment-512362602).

My question is: how would you handle cases of pagination looking like
```
 « [2] (p5.30-catalyst-plugin-authentication-store-dbic - p5.30-dist-zilla-plugin-modulebuildtiny-fallback) [3] (p5.30-dist-zilla-role-pluginbundle-pluginremover - p5.30-moosex-traitfor-meta-class-betteranonclassnames)
```
and still show a reasonable number of pages?

**Comment by mojca** [comment]
My response has been that if one knows what letter the port starts with, we should probably implement better filtering and allow entering `^c` as port name, which would then show all ports starting with the letter `c`, or `^co` to show all ports starting with `co`.

The only way I see the pagination work to some extent would be to show the port name after pointing the mouse to page number, but in any case we need to be careful not to inflate the number of database queries.

@lemzwerg: Do you have any example of another site already implementing something similar?

**Comment by lemzwerg** [comment]
Well, long names would be abbreviated:
```
« [2] (p5.30-catalyst-… – p5.30-dist-…) [3] (p5.30-dist-… – p5.30-moosex-…) ...
```
If there are so much packages in a category it would actually not be necessary to show ranges at all:
```
« [2] (p.30-catalyst…) [3] (p5.30-dist-…) ...
```
What I have in mind would be a rather rough guide to help navigation and nothing too detailed.

And no, I can't give an URL of a site that has something like that.

Your idea of filtering is nice, but it is heading into different direction.

**Comment by mojca** [comment]
While the idea is pretty interesting, I believe that it has a somewhat to low benefit-to-effort ratio, both because it might be a bit tricky to get it right and comfortable to use, and because the benefit doesn't seem that high. I believe it's still better to improve the search engine and allow better filtering / sorting by popularity, by broken builds, outdatedness etc.

I'm closing the ticket since I don't believe this might get implemented by random volunteers in any foreseeable future. But if someone submits a nice and functional pull requests, I don't really mind accepting it.
