### ISSUE TITLE
Tabbed views on Port-detail

### ISSUE THREAD

**Issue by arjunsalyan** [macports/macports-webapp#7]

**Comment by mojca** [comment]
Could we add at least some anchor to select a particular view? So that we could, say, link directly to the build status or statistics of a port? At the moment one can only link to the summary page.

Another minor request: can we add back the numbers of trac tickets? I would simply put the number at the front (on the left) and make it a clickable link to the trac ticket. With that in place maybe "View on Trac" can even go away.

**Comment by mojca** [comment]
I would also suggest printing the name and description of the port above the tabs and always have it visible, also when viewing the build or installation statistics, tickets etc. And maybe put `View on GitHub` to the right of port name?

Probably port health could also be above statistics.

![image](https://user-images.githubusercontent.com/15606/59549157-cc106a80-8f59-11e9-8e01-d43449776311.png)

**Comment by arjunsalyan** [comment]
> Another minor request: can we add back the numbers of trac tickets? I would simply put the number at the front (on the left) and make it a clickable link to the trac ticket. With that in place maybe "View on Trac" can even go away.

I will see if this is possible, thanks.
